plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.myapt'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j:8.3.0'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	/* 크롤링 */
	implementation 'org.jsoup:jsoup:1.15.4'

	/* OpenCSV */
	implementation 'com.opencsv:opencsv:5.7.1'

    /* Selenium WebDriver */
	implementation 'org.seleniumhq.selenium:selenium-java:4.29.0' // 최신 버전
	implementation 'io.github.bonigarcia:webdrivermanager:5.7.0'

	/*.xlsx 파일을 처리하려면 Apache POI와 같은 Excel 파일 처리 라이브러리 */
	implementation 'org.apache.poi:poi:5.2.5'
	implementation 'org.apache.poi:poi-ooxml:5.2.5'
}

tasks.named('test') {
	useJUnitPlatform()
}
