spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

news:
  api:
    client: ${news.api.client}
    secret: ${news.api.secret}

apt:
  api:
    base-url: ${APT_API_BASE_URL}  # 기본값 설정
    endpoint: ${APT_API_ENDPOINT}
    service-key: ${APT_API_SERVICE_KEY}  # 인증키는 환경 변수로 주입